services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - GIN_MODE=test
    ports:
      - "8080:8080"
    command: ["./app"] 

  test:
    build:
      context: .
      dockerfile: Dockerfile  
    depends_on:
      api:
        condition: service_started
    environment:
      - API_URL=http://api:8080
