name: Go API Tests with MongoDB

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      # Install Docker
      - name: Install Docker
        uses: docker/setup-buildx-action@v2
        with:
          install: true
      
      # Install Docker Compose
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version
      
      # Make test script executable
      - name: Make test script executable
        run: chmod +x ./run_tests.sh
      
      # Run the test script
      - name: Run tests
        run: ./run_tests.sh
      
      # Archive logs on failure
      - name: Archive logs on failure
        if: failure()
        run: |
          mkdir -p ./test-logs
          docker-compose logs > ./test-logs/docker-compose.log
          docker logs api > ./test-logs/api.log 2>&1 || true
          docker logs mongodb > ./test-logs/mongodb.log 2>&1 || true
          docker logs test > ./test-logs/test.log 2>&1 || true
      
      # Upload logs as artifacts
      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-logs
          path: ./test-logs/
          retention-days: 5
