name: API Basic Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Check project structure
      run: |
        if [ -f "Dockerfile" ] && [ -f "go.mod" ] && [ -f "main.go" ]; then
          echo "✓ Basic project structure check passed"
        else
          echo "✗ Missing required files"
          exit 1
        fi
      
    - name: Build Docker image
      run: docker build -t todo-api:test .
      
    - name: Test API endpoints
      run: |
        # Start container
        docker run -d -p 6400:6400 --name todo-api-test todo-api:test
        sleep 5
        
        # Test health endpoint
        health=$(curl -s http://localhost:6400/api/v1/health)
        echo "Health response: $health"
        
        if [[ "$health" != *"ok"* ]]; then
          echo "Health endpoint test failed"
          docker stop todo-api-test
          docker rm todo-api-test
          exit 1
        fi
        
      
        # Clean up
        docker stop todo-api-test
        docker rm todo-api-test
        
        echo "All tests passed!"